-- =====================================================
-- ELIMINACIÓN DE TABLAS
-- =====================================================
--he colocado esto al inicio, para eliminar versiones
--residuales de las tablas, cuando reciban los insert.sql, 
--deberán ejecutarlo tras ejecutar esto, o adjuntarlo en el
--mismo Script, [pueden desechar este comentario]

DROP TABLE telefono CASCADE CONSTRAINTS;
DROP TABLE asignacion CASCADE CONSTRAINTS;
DROP TABLE tarea CASCADE CONSTRAINTS;
DROP TABLE documento CASCADE CONSTRAINTS;
DROP TABLE riesgo CASCADE CONSTRAINTS;
DROP TABLE hito CASCADE CONSTRAINTS;
DROP TABLE empleado CASCADE CONSTRAINTS;
DROP TABLE proyecto CASCADE CONSTRAINTS;
DROP TABLE categoria CASCADE CONSTRAINTS;
DROP TABLE recurso CASCADE CONSTRAINTS;

-- =====================================================
-- TABLA: CATEGORIA
-- =====================================================

CREATE TABLE categoria (
    id_categoria NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY
            (START WITH 1000 INCREMENT BY 1)
            CONSTRAINT pk_categoria PRIMARY KEY,

    nombre_categoria VARCHAR2(100)
        CONSTRAINT nn_categoria_nombre NOT NULL,

    descripcion_categoria VARCHAR2(300)
);

-- =====================================================
-- TABLA: PROYECTO
-- =====================================================

CREATE TABLE proyecto (
    id_proyecto NUMBER
         GENERATED BY DEFAULT ON NULL AS IDENTITY
            (START WITH 1000 INCREMENT BY 1)
             CONSTRAINT pk_proyecto PRIMARY KEY,

    nombre_proyecto VARCHAR2(150)
        CONSTRAINT nn_proyecto_nombre NOT NULL,

    id_categoria NUMBER
        CONSTRAINT nn_proyecto_categoria NOT NULL,
    
    fecha_inicio DATE,
    
    fecha_fin DATE,

    presupuesto NUMBER(10,2)
        CONSTRAINT chk_presupuesto CHECK (presupuesto >= 0),

    estado_proyecto VARCHAR2(20)
        CONSTRAINT chk_estado_proyecto 
        CHECK (estado_proyecto IN ('POR_INICIAR','EN_DESARROLLO','FINALIZADO','EN_ESPERA')),

    CONSTRAINT fk_proyecto_categoria
        FOREIGN KEY (id_categoria)
        REFERENCES categoria(id_categoria)
);


-- =====================================================
-- TABLA: EMPLEADO
-- =====================================================

CREATE TABLE empleado (
    id_empleado NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY
            (START WITH 1000 INCREMENT BY 1)
        CONSTRAINT pk_empleado PRIMARY KEY,

    nombre VARCHAR2(100)
        CONSTRAINT nn_empleado_nombre NOT NULL,

    apellido VARCHAR2(100)
        CONSTRAINT nn_empleado_apellido NOT NULL,

    correo VARCHAR2(150)
        CONSTRAINT uq_empleado_correo UNIQUE,

    disponibilidad VARCHAR2(20)
        CONSTRAINT chk_empleado_disponibilidad 
        CHECK (disponibilidad IN ('DISPONIBLE','OCUPADO','EN_VACACIONES')),
    
    rol VARCHAR2(30)
    CONSTRAINT chk_empleado_rol
    CHECK (rol IN (
        'DESARROLLADOR',
        'ANALISTA',
        'GERENTE',
        'TESTER',
        'DISEÑADOR',
        'ADMINISTRADOR',
        'CONSTRUCTOR',
        'CONSULTOR',
        'PROMOTOR',
        'ARQUITECTO',
        'INGENIERO_CIVIL',
        'DIRECTOR_OBRA',
        'DIRECTOR_EJECUCION',
        'COORDINADOR_SEGURIDAD',
        'CONTRATISTA',
        'CAPATAZ',
        'ALBAÑIL',
        'ELECTRICISTA',
        'PLOMERO',
        'CARPINTERO',
        'SOLDADOR'
    ))
);

-- =====================================================
-- TABLA: TELEFONO
-- =====================================================

CREATE TABLE telefono (
    id_empleado NUMBER
        CONSTRAINT nn_telefono_empleado NOT NULL,

    telefono VARCHAR2(20)
        CONSTRAINT nn_telefono NOT NULL,

    CONSTRAINT pk_telefono
        PRIMARY KEY (id_empleado, telefono),

    CONSTRAINT fk_telefono_empleado
        FOREIGN KEY (id_empleado)
        REFERENCES empleado(id_empleado)
        ON DELETE CASCADE
);

-- =====================================================
-- TABLA: TAREA
-- =====================================================

CREATE TABLE tarea (
    id_tarea NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY
            (START WITH 1000 INCREMENT BY 1)
            CONSTRAINT pk_tarea PRIMARY KEY,

    id_proyecto NUMBER
        CONSTRAINT nn_tarea_proyecto NOT NULL,

    titulo_tarea VARCHAR2(150)
        CONSTRAINT nn_titulo_tarea NOT NULL,

    estado_tarea VARCHAR2(30)
        CONSTRAINT nn_estado_tarea NOT NULL,
        
    fecha_creacion DATE,
    
    fecha_entrega DATE,

    descripcion_tarea VARCHAR2(300),

    CONSTRAINT fk_tarea_proyecto
        FOREIGN KEY (id_proyecto)
        REFERENCES proyecto(id_proyecto)
        ON DELETE CASCADE,

    CONSTRAINT chk_estado_tarea
        CHECK (
            estado_tarea IN (
                
                'POR INICIAR',
                'EN DESARROLLO',
                'EN PAUSA',
                'FINALIZADO'
            )
        )
);

-- =====================================================
-- TABLA: RECURSO
-- =====================================================

CREATE TABLE recurso (
    id_recurso NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY
            (START WITH 1000 INCREMENT BY 1)
        CONSTRAINT pk_recurso PRIMARY KEY,

    nombre_recurso VARCHAR2(150)
        CONSTRAINT nn_nombre_recurso NOT NULL,

    tipo_recurso VARCHAR2(50)
        CONSTRAINT nn_tipo_recurso NOT NULL,
    
    descripcion_recurso VARCHAR2(300),

    disponibilidad_recurso VARCHAR2(20)
        CONSTRAINT chk_disponibilidad_recurso 
           CHECK (
               disponibilidad_recurso IN (
                'DISPONIBLE',
                'OCUPADO',
                'EN_MANTENIMIENTO'
            )
        )
);

-- =====================================================
-- TABLA: ASIGNACION
-- =====================================================

CREATE TABLE asignacion (
    id_tarea NUMBER
        CONSTRAINT nn_asignacion_tarea NOT NULL,

    id_empleado NUMBER
        CONSTRAINT nn_asignacion_empleado NOT NULL,

    id_recurso NUMBER
        CONSTRAINT nn_asignacion_recurso NOT NULL,

    horas_reales NUMBER(6,2)
        CONSTRAINT chk_horas_reales CHECK (horas_reales >= 0),

    horas_estimadas NUMBER(6,2)
        CONSTRAINT chk_horas_estimadas CHECK (horas_estimadas >= 0),

    CONSTRAINT pk_asignacion
        PRIMARY KEY (id_tarea, id_empleado),

    CONSTRAINT fk_asignacion_tarea
        FOREIGN KEY (id_tarea)
        REFERENCES tarea(id_tarea)
        ON DELETE CASCADE,

    CONSTRAINT fk_asignacion_empleado
        FOREIGN KEY (id_empleado)
        REFERENCES empleado(id_empleado)
        ON DELETE CASCADE,

    CONSTRAINT fk_asignacion_recurso
        FOREIGN KEY (id_recurso)
        REFERENCES recurso(id_recurso)
        ON DELETE CASCADE
);


-- =====================================================
-- TABLA: DOCUMENTO
-- =====================================================

CREATE TABLE documento (
    id_documento NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY
            (START WITH 1000 INCREMENT BY 1)
        CONSTRAINT pk_documento PRIMARY KEY,

    id_proyecto NUMBER
        CONSTRAINT nn_documento_proyecto NOT NULL,

    nombre_documento VARCHAR2(150)
        CONSTRAINT nn_documento_nombre NOT NULL,

    fecha_creacion DATE
        CONSTRAINT nn_documento_fecha NOT NULL,

    contenido CLOB
        CONSTRAINT nn_documento_contenido NOT NULL,

    CONSTRAINT fk_documento_proyecto
        FOREIGN KEY (id_proyecto)
        REFERENCES proyecto(id_proyecto)
        ON DELETE CASCADE
);


-- =====================================================
-- TABLA: RIESGO
-- =====================================================

CREATE TABLE riesgo (
     id_riesgo NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY
            (START WITH 1000 INCREMENT BY 1)
        CONSTRAINT pk_riesgo PRIMARY KEY,

    id_proyecto NUMBER
        CONSTRAINT nn_riesgo_proyecto NOT NULL,

    descripcion_riesgo VARCHAR2(300)
        CONSTRAINT nn_descripcion_riesgo NOT NULL,

    impacto VARCHAR2(30)
        CONSTRAINT nn_impacto_riesgo NOT NULL,
    
    probabilidad VARCHAR2(30)
        CONSTRAINT nn_probabilidad_riesgo NOT NULL,

    plan_mitigacion VARCHAR2(300)
        CONSTRAINT nn_plan_mitigacion NOT NULL,

    CONSTRAINT fk_riesgo_proyecto
        FOREIGN KEY (id_proyecto)
        REFERENCES proyecto(id_proyecto)
        ON DELETE CASCADE
);

-- =====================================================
-- TABLA: HITO
-- =====================================================

CREATE TABLE hito (
    id_hito NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY
            (START WITH 1000 INCREMENT BY 1)
        CONSTRAINT pk_hito PRIMARY KEY,

    id_proyecto NUMBER
        CONSTRAINT nn_hito_proyecto NOT NULL,

    nombre_hito VARCHAR2(150)
        CONSTRAINT nn_nombre_hito NOT NULL,
        
    fecha_hito DATE,
    

    CONSTRAINT fk_hito_proyecto
        FOREIGN KEY (id_proyecto)
        REFERENCES proyecto(id_proyecto)
        ON DELETE CASCADE
);


COMMIT;